# Bopomofo Keyboard Layout
BopomofoKeyboardLayout=standard
# Candidate List Layout
CandidateLayout=Vertical
# Selection Keys
SelectionKeys=123456789
# Selection Keys Count
SelectionKeysCount=9
# Space key chooses candidate
ChooseCandidateUsingSpace=True
# Show Candidates
SelectPhrase=after_cursor
# Move cursor after selection
MoveCursorAfterSelection=False
# When Choosing Candidates
AllowMovingCursorWhenChoosingCandidates="Moving cursor is not allowed"
# ESC key clears entire composing buffer
EscKeyClearsEntireComposingBuffer=True
# Allow typing in Chinese while Caps Lock is on (like MS IME)
capsLockAllowChineseInput=True
# Shift + Letter Keys
ShiftLetterKeys=put_lowercase_to_buffer
# Shift + Enter Key triggers associated phrases
ShitEnterEnabled=False
# Repeated punctuation to select next candidate
RepeatedPunctuationToSelectCandidateEnabled=False
# Control + Enter Key
KeyHandlerCtrlEnter=disabled
# Open User Phrase Files With
OpenUserPhraseFilesWith=xdg-open
# Add Phrase Hook Path
AddScriptHookPath=/usr/share/fcitx5/data/mcbopomofo-add-phrase-hook.sh
# Run the hook script after adding a phrase
AddScriptHookEnabled=False
# Enable Half Width Punctuation
HalfWidthPunctuationEnable=False
# Enable Associated Phrases
AssociatedPhrasesEnabled=False

