# Monitors
# See https://wiki.hypr.land/Configuring/Monitors/
monitorv2 {
    output = DP-1
    mode = 2560x1440@165
    position = 1920x0
    scale = 1.25

    disabled = false
}

monitorv2 {
    output = HDMI-A-2
    mode = 1920x1080@60
    position = 0x480
    scale = 1
    
    disabled = false
}

monitorv2 {
    output =
    mode = preferred
    position = auto
    scale = auto
}

# Other devices
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = asustek-rog-omni-receiver
    sensitivity = -0.65
}
