# Monitors
# See https://wiki.hypr.land/Configuring/Monitors/
monitorv2 {
    output = DP-1
    mode = 2560x1440@165
    position = 1920x0
    scale = 1.25
    # cm = hdredid

    disabled = false
}

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@75
    position = 0x400
    scale = 1
    
    disabled = false
}

monitorv2 {
    output =
    mode = preferred
    position = auto
    scale = 1
}

# Other devices
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = asustek-rog-omni-receiver
    sensitivity = -0.65
}
